# -*- coding: utf-8 -*-
"""CV Scorer.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bEmbYQ5Axe_5QA6kcqPkZBcaNBFdWSqB
"""

!pip install docx2txt

import docx2txt

JD = docx2txt.process("Data Scientist_JD.docx")

JD

resume = docx2txt.process("Ameesha Muthanna.docx")

resume

# create a list of text
text=[resume, JD]

# create a count vector object to count each word in the text
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
count_matrix =cv.fit_transform(text)

# import sklearn to use the cosine similarity function
from sklearn.metrics.pairwise import cosine_similarity

# print the similarity scores
print("\nSimilarity score:")
print(cosine_similarity(count_matrix))

# get the match percentage
matchPercentage = cosine_similarity(count_matrix)[0][1]*100
matchPercentage = round(matchPercentage, 2) # round to 2 decimal places
print("your resume matches about " + str(matchPercentage) + " % for the required profile.")







